appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=[%(executionTime)ms] %(category) | %(sqlSingleLine)
excludecategories=info,debug,result,resultset,batch,commit,rollback
